INKSCAPE?=inkscape
OPTIPNG?=optipng -o7 --strip all --quiet
SCSS?=sassc

DEFAULT_THEME_COLOR?=\#2777ff
COLOR_VARIANTS ?= Blue Green Teal Yellow

UNWANTED_VARIANTS ?= White-Light Black-Dark

COLOR_Blue?=\#2777ff
TEXT_COLOR_Blue?=\#ffffff

COLOR_Green?=\#06a284
TEXT_COLOR_Green?=\#ffffff

COLOR_Teal?=\#0099a1
TEXT_COLOR_Teal?=\#ffffff

COLOR_Yellow?=\#ffd86e
TEXT_COLOR_Yellow?=\#000000
